[zigbee]
port = "/dev/serial/by-id/usb-SONOFF_Zigbee_3.0_USB_Dongle_Plus-if00-port0"
baudrate = 115200

[insteon]
port = "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART-if00-port0"

# SPDX-License-Identifier: Apache-2.0

[bridge]
optimistic_hue_updates = true
echo_suppression_ms = 750

[[banks]]
id = "bank_a"
name = "Insteon Bank A"
endpoint = 1
insteon_address = "11.22.33"
default_level = 254

[[banks]]
id = "bank_b"
name = "Insteon Bank B"
endpoint = 2
insteon_address = "22.33.44"
default_level = 254

[[banks]]
id = "bank_c"
name = "Insteon Bank C"
endpoint = 3
insteon_address = "33.44.55"
default_level = 254
